
from src.classifiers.bank_statement_classifier import BankStatementClassifier
from src.classifiers.driving_license_classifier import DrivingLicenseClassifier
from src.classifiers.invoice_classifier import InvoiceClassifier